[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }

serde = { workspace = true }
cbor4ii = { workspace = true }
serde_json = { workspace = true }

log = { workspace = true }

common-protocol = { workspace = true }
common-pow = { workspace = true }

tokio = { workspace = true }

simple_logger = "4.0.0"
lazy_static = "1.4.0"
rand = "0.8.5"
chrono = {version = "0.4.23", features = ["serde"]}
magic-crypt = "3.1.12"

dotenv = "0.15.0"