[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }

serde = { workspace = true }
cbor4ii = { workspace = true }
serde_json = { workspace = true }
base64 = "0.21.0"

log = { workspace = true }

common-protocol = { workspace = true }
common-pow = { workspace = true }

rayon = "1.6.1"
tokio = { workspace = true }
tokio-util = { version = "0.7.4", features = ["codec"] }
futures = "0.3.26"
bytes = "1.3.0"

simple_logger = "4.0.0"
dotenv = "0.15.0"